version: "3.8"

services:
  backend:
    build:
      context: .  # Context . = project root
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app    # Live code sync for development
    networks:
      - job-network

  frontend:
    build:
      context: ./jobtrackr-frontend  # only builds inside the frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - job-network  # Allows frontend <-> backend communication

networks:
  job-network: